
package com.linkedin.assertion;

import java.util.List;
import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.linkedin.data.DataMap;
import com.linkedin.data.collections.CheckedUtil;
import com.linkedin.data.schema.MaskMap;
import com.linkedin.data.schema.PathSpec;
import com.linkedin.data.schema.RecordDataSchema;
import com.linkedin.data.schema.SchemaFormatType;
import com.linkedin.data.template.DataTemplateUtil;
import com.linkedin.data.template.GetMode;
import com.linkedin.data.template.RecordTemplate;
import com.linkedin.data.template.RequiredFieldNotPresentException;
import com.linkedin.data.template.SetMode;


/**
 * Attributes defining a CRON-formatted schedule used for defining a freshness assertion.
 * 
 */
@Generated(value = "com.linkedin.pegasus.generator.JavaCodeUtil", comments = "Rest.li Data Template. Generated from metadata-models/src/main/pegasus/com/linkedin/assertion/FreshnessCronSchedule.pdl.")
public class FreshnessCronSchedule
    extends RecordTemplate
{

    private final static FreshnessCronSchedule.Fields _fields = new FreshnessCronSchedule.Fields();
    private final static RecordDataSchema SCHEMA = ((RecordDataSchema) DataTemplateUtil.parseSchema("namespace com.linkedin.assertion/**Attributes defining a CRON-formatted schedule used for defining a freshness assertion.*/record FreshnessCronSchedule{/**A cron-formatted execution interval, as a cron string, e.g. 1 * * * **/cron:string/**Timezone in which the cron interval applies, e.g. America/Los Angeles*/timezone:string/**An optional offset in milliseconds to SUBTRACT from the timestamp generated by the cron schedule\nto generate the lower bounds of the \"freshness window\", or the window of time in which an event must have occurred in order for the Freshness check\nto be considering passing.\n\nIf left empty, the start of the SLA window will be the _end_ of the previously evaluated Freshness window.*/windowStartOffsetMs:optional long}", SchemaFormatType.PDL));
    private String _cronField = null;
    private String _timezoneField = null;
    private Long _windowStartOffsetMsField = null;
    private FreshnessCronSchedule.ChangeListener __changeListener = new FreshnessCronSchedule.ChangeListener(this);
    private final static RecordDataSchema.Field FIELD_Cron = SCHEMA.getField("cron");
    private final static RecordDataSchema.Field FIELD_Timezone = SCHEMA.getField("timezone");
    private final static RecordDataSchema.Field FIELD_WindowStartOffsetMs = SCHEMA.getField("windowStartOffsetMs");

    public FreshnessCronSchedule() {
        super(new DataMap(4, 0.75F), SCHEMA);
        addChangeListener(__changeListener);
    }

    public FreshnessCronSchedule(DataMap data) {
        super(data, SCHEMA);
        addChangeListener(__changeListener);
    }

    public static FreshnessCronSchedule.Fields fields() {
        return _fields;
    }

    public static FreshnessCronSchedule.ProjectionMask createMask() {
        return new FreshnessCronSchedule.ProjectionMask();
    }

    public static RecordDataSchema dataSchema() {
        return SCHEMA;
    }

    /**
     * Existence checker for cron
     * 
     * @see FreshnessCronSchedule.Fields#cron
     */
    public boolean hasCron() {
        if (_cronField!= null) {
            return true;
        }
        return super._map.containsKey("cron");
    }

    /**
     * Remover for cron
     * 
     * @see FreshnessCronSchedule.Fields#cron
     */
    public void removeCron() {
        super._map.remove("cron");
    }

    /**
     * Getter for cron
     * 
     * @see FreshnessCronSchedule.Fields#cron
     */
    @Nullable
    public String getCron(GetMode mode) {
        switch (mode) {
            case STRICT:
                return getCron();
            case DEFAULT:
            case NULL:
                if (_cronField!= null) {
                    return _cronField;
                } else {
                    Object __rawValue = super._map.get("cron");
                    _cronField = DataTemplateUtil.coerceStringOutput(__rawValue);
                    return _cronField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for cron
     * 
     * @return
     *     Required field. Could be null for partial record.
     * @see FreshnessCronSchedule.Fields#cron
     */
    @Nonnull
    public String getCron() {
        if (_cronField!= null) {
            return _cronField;
        } else {
            Object __rawValue = super._map.get("cron");
            if (__rawValue == null) {
                throw new RequiredFieldNotPresentException("cron");
            }
            _cronField = DataTemplateUtil.coerceStringOutput(__rawValue);
            return _cronField;
        }
    }

    /**
     * Setter for cron
     * 
     * @see FreshnessCronSchedule.Fields#cron
     */
    public FreshnessCronSchedule setCron(
        @Nullable
        String value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setCron(value);
            case REMOVE_OPTIONAL_IF_NULL:
                if (value == null) {
                    throw new IllegalArgumentException("Cannot remove mandatory field cron of com.linkedin.assertion.FreshnessCronSchedule");
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "cron", value);
                    _cronField = value;
                }
                break;
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeCron();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "cron", value);
                    _cronField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "cron", value);
                    _cronField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for cron
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see FreshnessCronSchedule.Fields#cron
     */
    public FreshnessCronSchedule setCron(
        @Nonnull
        String value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field cron of com.linkedin.assertion.FreshnessCronSchedule to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "cron", value);
            _cronField = value;
        }
        return this;
    }

    /**
     * Existence checker for timezone
     * 
     * @see FreshnessCronSchedule.Fields#timezone
     */
    public boolean hasTimezone() {
        if (_timezoneField!= null) {
            return true;
        }
        return super._map.containsKey("timezone");
    }

    /**
     * Remover for timezone
     * 
     * @see FreshnessCronSchedule.Fields#timezone
     */
    public void removeTimezone() {
        super._map.remove("timezone");
    }

    /**
     * Getter for timezone
     * 
     * @see FreshnessCronSchedule.Fields#timezone
     */
    @Nullable
    public String getTimezone(GetMode mode) {
        switch (mode) {
            case STRICT:
                return getTimezone();
            case DEFAULT:
            case NULL:
                if (_timezoneField!= null) {
                    return _timezoneField;
                } else {
                    Object __rawValue = super._map.get("timezone");
                    _timezoneField = DataTemplateUtil.coerceStringOutput(__rawValue);
                    return _timezoneField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for timezone
     * 
     * @return
     *     Required field. Could be null for partial record.
     * @see FreshnessCronSchedule.Fields#timezone
     */
    @Nonnull
    public String getTimezone() {
        if (_timezoneField!= null) {
            return _timezoneField;
        } else {
            Object __rawValue = super._map.get("timezone");
            if (__rawValue == null) {
                throw new RequiredFieldNotPresentException("timezone");
            }
            _timezoneField = DataTemplateUtil.coerceStringOutput(__rawValue);
            return _timezoneField;
        }
    }

    /**
     * Setter for timezone
     * 
     * @see FreshnessCronSchedule.Fields#timezone
     */
    public FreshnessCronSchedule setTimezone(
        @Nullable
        String value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setTimezone(value);
            case REMOVE_OPTIONAL_IF_NULL:
                if (value == null) {
                    throw new IllegalArgumentException("Cannot remove mandatory field timezone of com.linkedin.assertion.FreshnessCronSchedule");
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "timezone", value);
                    _timezoneField = value;
                }
                break;
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeTimezone();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "timezone", value);
                    _timezoneField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "timezone", value);
                    _timezoneField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for timezone
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see FreshnessCronSchedule.Fields#timezone
     */
    public FreshnessCronSchedule setTimezone(
        @Nonnull
        String value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field timezone of com.linkedin.assertion.FreshnessCronSchedule to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "timezone", value);
            _timezoneField = value;
        }
        return this;
    }

    /**
     * Existence checker for windowStartOffsetMs
     * 
     * @see FreshnessCronSchedule.Fields#windowStartOffsetMs
     */
    public boolean hasWindowStartOffsetMs() {
        if (_windowStartOffsetMsField!= null) {
            return true;
        }
        return super._map.containsKey("windowStartOffsetMs");
    }

    /**
     * Remover for windowStartOffsetMs
     * 
     * @see FreshnessCronSchedule.Fields#windowStartOffsetMs
     */
    public void removeWindowStartOffsetMs() {
        super._map.remove("windowStartOffsetMs");
    }

    /**
     * Getter for windowStartOffsetMs
     * 
     * @see FreshnessCronSchedule.Fields#windowStartOffsetMs
     */
    @Nullable
    public Long getWindowStartOffsetMs(GetMode mode) {
        return getWindowStartOffsetMs();
    }

    /**
     * Getter for windowStartOffsetMs
     * 
     * @return
     *     Optional field. Always check for null.
     * @see FreshnessCronSchedule.Fields#windowStartOffsetMs
     */
    @Nullable
    public Long getWindowStartOffsetMs() {
        if (_windowStartOffsetMsField!= null) {
            return _windowStartOffsetMsField;
        } else {
            Object __rawValue = super._map.get("windowStartOffsetMs");
            _windowStartOffsetMsField = DataTemplateUtil.coerceLongOutput(__rawValue);
            return _windowStartOffsetMsField;
        }
    }

    /**
     * Setter for windowStartOffsetMs
     * 
     * @see FreshnessCronSchedule.Fields#windowStartOffsetMs
     */
    public FreshnessCronSchedule setWindowStartOffsetMs(
        @Nullable
        Long value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setWindowStartOffsetMs(value);
            case REMOVE_OPTIONAL_IF_NULL:
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeWindowStartOffsetMs();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "windowStartOffsetMs", DataTemplateUtil.coerceLongInput(value));
                    _windowStartOffsetMsField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "windowStartOffsetMs", DataTemplateUtil.coerceLongInput(value));
                    _windowStartOffsetMsField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for windowStartOffsetMs
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see FreshnessCronSchedule.Fields#windowStartOffsetMs
     */
    public FreshnessCronSchedule setWindowStartOffsetMs(
        @Nonnull
        Long value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field windowStartOffsetMs of com.linkedin.assertion.FreshnessCronSchedule to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "windowStartOffsetMs", DataTemplateUtil.coerceLongInput(value));
            _windowStartOffsetMsField = value;
        }
        return this;
    }

    /**
     * Setter for windowStartOffsetMs
     * 
     * @see FreshnessCronSchedule.Fields#windowStartOffsetMs
     */
    public FreshnessCronSchedule setWindowStartOffsetMs(long value) {
        CheckedUtil.putWithoutChecking(super._map, "windowStartOffsetMs", DataTemplateUtil.coerceLongInput(value));
        _windowStartOffsetMsField = value;
        return this;
    }

    @Override
    public FreshnessCronSchedule clone()
        throws CloneNotSupportedException
    {
        FreshnessCronSchedule __clone = ((FreshnessCronSchedule) super.clone());
        __clone.__changeListener = new FreshnessCronSchedule.ChangeListener(__clone);
        __clone.addChangeListener(__clone.__changeListener);
        return __clone;
    }

    @Override
    public FreshnessCronSchedule copy()
        throws CloneNotSupportedException
    {
        FreshnessCronSchedule __copy = ((FreshnessCronSchedule) super.copy());
        __copy._cronField = null;
        __copy._timezoneField = null;
        __copy._windowStartOffsetMsField = null;
        __copy.__changeListener = new FreshnessCronSchedule.ChangeListener(__copy);
        __copy.addChangeListener(__copy.__changeListener);
        return __copy;
    }

    private static class ChangeListener
        implements com.linkedin.data.collections.CheckedMap.ChangeListener<String, Object>
    {

        private final FreshnessCronSchedule __objectRef;

        private ChangeListener(FreshnessCronSchedule reference) {
            __objectRef = reference;
        }

        @Override
        public void onUnderlyingMapChanged(String key, Object value) {
            switch (key) {
                case "cron":
                    __objectRef._cronField = null;
                    break;
                case "timezone":
                    __objectRef._timezoneField = null;
                    break;
                case "windowStartOffsetMs":
                    __objectRef._windowStartOffsetMsField = null;
                    break;
            }
        }

    }

    public static class Fields
        extends PathSpec
    {


        public Fields(List<String> path, String name) {
            super(path, name);
        }

        public Fields() {
            super();
        }

        /**
         * A cron-formatted execution interval, as a cron string, e.g. 1 * * * *
         * 
         */
        public PathSpec cron() {
            return new PathSpec(getPathComponents(), "cron");
        }

        /**
         * Timezone in which the cron interval applies, e.g. America/Los Angeles
         * 
         */
        public PathSpec timezone() {
            return new PathSpec(getPathComponents(), "timezone");
        }

        /**
         * An optional offset in milliseconds to SUBTRACT from the timestamp generated by the cron schedule
         * to generate the lower bounds of the "freshness window", or the window of time in which an event must have occurred in order for the Freshness check
         * to be considering passing.
         * 
         * If left empty, the start of the SLA window will be the _end_ of the previously evaluated Freshness window.
         * 
         */
        public PathSpec windowStartOffsetMs() {
            return new PathSpec(getPathComponents(), "windowStartOffsetMs");
        }

    }

    public static class ProjectionMask
        extends MaskMap
    {


        ProjectionMask() {
            super(4);
        }

        /**
         * A cron-formatted execution interval, as a cron string, e.g. 1 * * * *
         * 
         */
        public FreshnessCronSchedule.ProjectionMask withCron() {
            getDataMap().put("cron", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * Timezone in which the cron interval applies, e.g. America/Los Angeles
         * 
         */
        public FreshnessCronSchedule.ProjectionMask withTimezone() {
            getDataMap().put("timezone", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * An optional offset in milliseconds to SUBTRACT from the timestamp generated by the cron schedule
         * to generate the lower bounds of the "freshness window", or the window of time in which an event must have occurred in order for the Freshness check
         * to be considering passing.
         * 
         * If left empty, the start of the SLA window will be the _end_ of the previously evaluated Freshness window.
         * 
         */
        public FreshnessCronSchedule.ProjectionMask withWindowStartOffsetMs() {
            getDataMap().put("windowStartOffsetMs", MaskMap.POSITIVE_MASK);
            return this;
        }

    }

}
