
package com.linkedin.timeseries;

import java.util.List;
import java.util.function.Function;
import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.linkedin.data.DataMap;
import com.linkedin.data.collections.CheckedUtil;
import com.linkedin.data.schema.MaskMap;
import com.linkedin.data.schema.PathSpec;
import com.linkedin.data.schema.RecordDataSchema;
import com.linkedin.data.schema.SchemaFormatType;
import com.linkedin.data.template.DataTemplateUtil;
import com.linkedin.data.template.GetMode;
import com.linkedin.data.template.RecordTemplate;
import com.linkedin.data.template.RequiredFieldNotPresentException;
import com.linkedin.data.template.SetMode;


/**
 * A reference to a specific partition in a dataset.
 * 
 */
@Generated(value = "com.linkedin.pegasus.generator.JavaCodeUtil", comments = "Rest.li Data Template. Generated from metadata-models/src/main/pegasus/com/linkedin/timeseries/PartitionSpec.pdl.")
public class PartitionSpec
    extends RecordTemplate
{

    private final static PartitionSpec.Fields _fields = new PartitionSpec.Fields();
    private final static RecordDataSchema SCHEMA = ((RecordDataSchema) DataTemplateUtil.parseSchema("namespace com.linkedin.timeseries/**A reference to a specific partition in a dataset.*/record PartitionSpec{/**A unique id / value for the partition for which statistics were collected,\ngenerated by applying the key definition to a given row.*/@TimeseriesField={}partition:string/**Time window of the partition, if we are able to extract it from the partition key.*/timePartition:optional record TimeWindow{/**Start time as epoch at UTC.*/startTimeMillis:long/**The length of the window.*/length:/**Defines the size of a time window.*/record TimeWindowSize{/**Interval unit such as minute/hour/day etc.*/unit:enum CalendarInterval{SECOND,MINUTE,HOUR,DAY,WEEK,MONTH,QUARTER,YEAR}/**How many units. Defaults to 1.*/multiple:int=1}}/**Unused!*/@deprecated,type:enum PartitionType{FULL_TABLE,QUERY,PARTITION}=\"PARTITION\"}", SchemaFormatType.PDL));
    private String _partitionField = null;
    private TimeWindow _timePartitionField = null;
    private PartitionType _typeField = null;
    private PartitionSpec.ChangeListener __changeListener = new PartitionSpec.ChangeListener(this);
    private final static RecordDataSchema.Field FIELD_Partition = SCHEMA.getField("partition");
    private final static RecordDataSchema.Field FIELD_TimePartition = SCHEMA.getField("timePartition");
    private final static RecordDataSchema.Field FIELD_Type = SCHEMA.getField("type");
    private final static PartitionType DEFAULT_Type;

    static {
        DEFAULT_Type = DataTemplateUtil.coerceEnumOutput(FIELD_Type.getDefault(), PartitionType.class, PartitionType.$UNKNOWN);
    }

    public PartitionSpec() {
        super(new DataMap(4, 0.75F), SCHEMA, 2);
        addChangeListener(__changeListener);
    }

    public PartitionSpec(DataMap data) {
        super(data, SCHEMA);
        addChangeListener(__changeListener);
    }

    public static PartitionSpec.Fields fields() {
        return _fields;
    }

    public static PartitionSpec.ProjectionMask createMask() {
        return new PartitionSpec.ProjectionMask();
    }

    public static RecordDataSchema dataSchema() {
        return SCHEMA;
    }

    /**
     * Existence checker for partition
     * 
     * @see PartitionSpec.Fields#partition
     */
    public boolean hasPartition() {
        if (_partitionField!= null) {
            return true;
        }
        return super._map.containsKey("partition");
    }

    /**
     * Remover for partition
     * 
     * @see PartitionSpec.Fields#partition
     */
    public void removePartition() {
        super._map.remove("partition");
    }

    /**
     * Getter for partition
     * 
     * @see PartitionSpec.Fields#partition
     */
    @Nullable
    public String getPartition(GetMode mode) {
        switch (mode) {
            case STRICT:
                return getPartition();
            case DEFAULT:
            case NULL:
                if (_partitionField!= null) {
                    return _partitionField;
                } else {
                    Object __rawValue = super._map.get("partition");
                    _partitionField = DataTemplateUtil.coerceStringOutput(__rawValue);
                    return _partitionField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for partition
     * 
     * @return
     *     Required field. Could be null for partial record.
     * @see PartitionSpec.Fields#partition
     */
    @Nonnull
    public String getPartition() {
        if (_partitionField!= null) {
            return _partitionField;
        } else {
            Object __rawValue = super._map.get("partition");
            if (__rawValue == null) {
                throw new RequiredFieldNotPresentException("partition");
            }
            _partitionField = DataTemplateUtil.coerceStringOutput(__rawValue);
            return _partitionField;
        }
    }

    /**
     * Setter for partition
     * 
     * @see PartitionSpec.Fields#partition
     */
    public PartitionSpec setPartition(
        @Nullable
        String value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setPartition(value);
            case REMOVE_OPTIONAL_IF_NULL:
                if (value == null) {
                    throw new IllegalArgumentException("Cannot remove mandatory field partition of com.linkedin.timeseries.PartitionSpec");
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "partition", value);
                    _partitionField = value;
                }
                break;
            case REMOVE_IF_NULL:
                if (value == null) {
                    removePartition();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "partition", value);
                    _partitionField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "partition", value);
                    _partitionField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for partition
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see PartitionSpec.Fields#partition
     */
    public PartitionSpec setPartition(
        @Nonnull
        String value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field partition of com.linkedin.timeseries.PartitionSpec to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "partition", value);
            _partitionField = value;
        }
        return this;
    }

    /**
     * Existence checker for timePartition
     * 
     * @see PartitionSpec.Fields#timePartition
     */
    public boolean hasTimePartition() {
        if (_timePartitionField!= null) {
            return true;
        }
        return super._map.containsKey("timePartition");
    }

    /**
     * Remover for timePartition
     * 
     * @see PartitionSpec.Fields#timePartition
     */
    public void removeTimePartition() {
        super._map.remove("timePartition");
    }

    /**
     * Getter for timePartition
     * 
     * @see PartitionSpec.Fields#timePartition
     */
    @Nullable
    public TimeWindow getTimePartition(GetMode mode) {
        return getTimePartition();
    }

    /**
     * Getter for timePartition
     * 
     * @return
     *     Optional field. Always check for null.
     * @see PartitionSpec.Fields#timePartition
     */
    @Nullable
    public TimeWindow getTimePartition() {
        if (_timePartitionField!= null) {
            return _timePartitionField;
        } else {
            Object __rawValue = super._map.get("timePartition");
            _timePartitionField = ((__rawValue == null)?null:new TimeWindow(DataTemplateUtil.castOrThrow(__rawValue, DataMap.class)));
            return _timePartitionField;
        }
    }

    /**
     * Setter for timePartition
     * 
     * @see PartitionSpec.Fields#timePartition
     */
    public PartitionSpec setTimePartition(
        @Nullable
        TimeWindow value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setTimePartition(value);
            case REMOVE_OPTIONAL_IF_NULL:
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeTimePartition();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "timePartition", value.data());
                    _timePartitionField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "timePartition", value.data());
                    _timePartitionField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for timePartition
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see PartitionSpec.Fields#timePartition
     */
    public PartitionSpec setTimePartition(
        @Nonnull
        TimeWindow value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field timePartition of com.linkedin.timeseries.PartitionSpec to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "timePartition", value.data());
            _timePartitionField = value;
        }
        return this;
    }

    /**
     * Existence checker for type
     * 
     * @see PartitionSpec.Fields#type
     */
    @Deprecated
    public boolean hasType() {
        if (_typeField!= null) {
            return true;
        }
        return super._map.containsKey("type");
    }

    /**
     * Remover for type
     * 
     * @see PartitionSpec.Fields#type
     */
    @Deprecated
    public void removeType() {
        super._map.remove("type");
    }

    /**
     * Getter for type
     * 
     * @see PartitionSpec.Fields#type
     */
    @Deprecated
    @Nullable
    public PartitionType getType(GetMode mode) {
        switch (mode) {
            case STRICT:
            case DEFAULT:
                return getType();
            case NULL:
                if (_typeField!= null) {
                    return _typeField;
                } else {
                    Object __rawValue = super._map.get("type");
                    _typeField = DataTemplateUtil.coerceEnumOutput(__rawValue, PartitionType.class, PartitionType.$UNKNOWN);
                    return _typeField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for type
     * 
     * @return
     *     Required field. Could be null for partial record.
     * @see PartitionSpec.Fields#type
     */
    @Deprecated
    @Nonnull
    public PartitionType getType() {
        if (_typeField!= null) {
            return _typeField;
        } else {
            Object __rawValue = super._map.get("type");
            if (__rawValue == null) {
                return DEFAULT_Type;
            }
            _typeField = DataTemplateUtil.coerceEnumOutput(__rawValue, PartitionType.class, PartitionType.$UNKNOWN);
            return _typeField;
        }
    }

    /**
     * Setter for type
     * 
     * @see PartitionSpec.Fields#type
     */
    @Deprecated
    public PartitionSpec setType(
        @Nullable
        PartitionType value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setType(value);
            case REMOVE_OPTIONAL_IF_NULL:
                if (value == null) {
                    throw new IllegalArgumentException("Cannot remove mandatory field type of com.linkedin.timeseries.PartitionSpec");
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "type", value.name());
                    _typeField = value;
                }
                break;
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeType();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "type", value.name());
                    _typeField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "type", value.name());
                    _typeField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for type
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see PartitionSpec.Fields#type
     */
    @Deprecated
    public PartitionSpec setType(
        @Nonnull
        PartitionType value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field type of com.linkedin.timeseries.PartitionSpec to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "type", value.name());
            _typeField = value;
        }
        return this;
    }

    @Override
    public PartitionSpec clone()
        throws CloneNotSupportedException
    {
        PartitionSpec __clone = ((PartitionSpec) super.clone());
        __clone.__changeListener = new PartitionSpec.ChangeListener(__clone);
        __clone.addChangeListener(__clone.__changeListener);
        return __clone;
    }

    @Override
    public PartitionSpec copy()
        throws CloneNotSupportedException
    {
        PartitionSpec __copy = ((PartitionSpec) super.copy());
        __copy._partitionField = null;
        __copy._typeField = null;
        __copy._timePartitionField = null;
        __copy.__changeListener = new PartitionSpec.ChangeListener(__copy);
        __copy.addChangeListener(__copy.__changeListener);
        return __copy;
    }

    private static class ChangeListener
        implements com.linkedin.data.collections.CheckedMap.ChangeListener<String, Object>
    {

        private final PartitionSpec __objectRef;

        private ChangeListener(PartitionSpec reference) {
            __objectRef = reference;
        }

        @Override
        public void onUnderlyingMapChanged(String key, Object value) {
            switch (key) {
                case "partition":
                    __objectRef._partitionField = null;
                    break;
                case "type":
                    __objectRef._typeField = null;
                    break;
                case "timePartition":
                    __objectRef._timePartitionField = null;
                    break;
            }
        }

    }

    public static class Fields
        extends PathSpec
    {


        public Fields(List<String> path, String name) {
            super(path, name);
        }

        public Fields() {
            super();
        }

        /**
         * A unique id / value for the partition for which statistics were collected,
         * generated by applying the key definition to a given row.
         * 
         */
        public PathSpec partition() {
            return new PathSpec(getPathComponents(), "partition");
        }

        /**
         * Time window of the partition, if we are able to extract it from the partition key.
         * 
         */
        public com.linkedin.timeseries.TimeWindow.Fields timePartition() {
            return new com.linkedin.timeseries.TimeWindow.Fields(getPathComponents(), "timePartition");
        }

        /**
         * Unused!
         * 
         */
        @Deprecated
        public PathSpec type() {
            return new PathSpec(getPathComponents(), "type");
        }

    }

    public static class ProjectionMask
        extends MaskMap
    {

        private com.linkedin.timeseries.TimeWindow.ProjectionMask _timePartitionMask;

        ProjectionMask() {
            super(4);
        }

        /**
         * A unique id / value for the partition for which statistics were collected,
         * generated by applying the key definition to a given row.
         * 
         */
        public PartitionSpec.ProjectionMask withPartition() {
            getDataMap().put("partition", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * Time window of the partition, if we are able to extract it from the partition key.
         * 
         */
        public PartitionSpec.ProjectionMask withTimePartition(Function<com.linkedin.timeseries.TimeWindow.ProjectionMask, com.linkedin.timeseries.TimeWindow.ProjectionMask> nestedMask) {
            _timePartitionMask = nestedMask.apply(((_timePartitionMask == null)?TimeWindow.createMask():_timePartitionMask));
            getDataMap().put("timePartition", _timePartitionMask.getDataMap());
            return this;
        }

        /**
         * Time window of the partition, if we are able to extract it from the partition key.
         * 
         */
        public PartitionSpec.ProjectionMask withTimePartition() {
            _timePartitionMask = null;
            getDataMap().put("timePartition", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * Unused!
         * 
         */
        @Deprecated
        public PartitionSpec.ProjectionMask withType() {
            getDataMap().put("type", MaskMap.POSITIVE_MASK);
            return this;
        }

    }

}
