
package com.linkedin.timeseries;

import java.util.List;
import java.util.function.Function;
import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.linkedin.data.DataMap;
import com.linkedin.data.collections.CheckedUtil;
import com.linkedin.data.schema.MaskMap;
import com.linkedin.data.schema.PathSpec;
import com.linkedin.data.schema.RecordDataSchema;
import com.linkedin.data.schema.SchemaFormatType;
import com.linkedin.data.template.DataTemplateUtil;
import com.linkedin.data.template.GetMode;
import com.linkedin.data.template.RecordTemplate;
import com.linkedin.data.template.RequiredFieldNotPresentException;
import com.linkedin.data.template.SetMode;


/**
 * 
 * 
 */
@Generated(value = "com.linkedin.pegasus.generator.JavaCodeUtil", comments = "Rest.li Data Template. Generated from metadata-models/src/main/pegasus/com/linkedin/timeseries/TimeseriesAspectBase.pdl.")
public class TimeseriesAspectBase
    extends RecordTemplate
{

    private final static TimeseriesAspectBase.Fields _fields = new TimeseriesAspectBase.Fields();
    private final static RecordDataSchema SCHEMA = ((RecordDataSchema) DataTemplateUtil.parseSchema("namespace com.linkedin.timeseries,record TimeseriesAspectBase{/**The event timestamp field as epoch at UTC in milli seconds.*/timestampMillis:long/**Granularity of the event if applicable*/eventGranularity:optional/**Defines the size of a time window.*/record TimeWindowSize{/**Interval unit such as minute/hour/day etc.*/unit:enum CalendarInterval{SECOND,MINUTE,HOUR,DAY,WEEK,MONTH,QUARTER,YEAR}/**How many units. Defaults to 1.*/multiple:int=1}/**The optional partition specification.*/partitionSpec:optional/**A reference to a specific partition in a dataset.*/record PartitionSpec{/**A unique id / value for the partition for which statistics were collected,\ngenerated by applying the key definition to a given row.*/@TimeseriesField={}partition:string/**Time window of the partition, if we are able to extract it from the partition key.*/timePartition:optional record TimeWindow{/**Start time as epoch at UTC.*/startTimeMillis:long/**The length of the window.*/length:TimeWindowSize}/**Unused!*/@deprecated,type:enum PartitionType{FULL_TABLE,QUERY,PARTITION}=\"PARTITION\"}={\"partition\":\"FULL_TABLE_SNAPSHOT\",\"type\":\"FULL_TABLE\"}/**The optional messageId, if provided serves as a custom user-defined unique identifier for an aspect value.*/messageId:optional string}", SchemaFormatType.PDL));
    private Long _timestampMillisField = null;
    private TimeWindowSize _eventGranularityField = null;
    private PartitionSpec _partitionSpecField = null;
    private String _messageIdField = null;
    private TimeseriesAspectBase.ChangeListener __changeListener = new TimeseriesAspectBase.ChangeListener(this);
    private final static RecordDataSchema.Field FIELD_TimestampMillis = SCHEMA.getField("timestampMillis");
    private final static RecordDataSchema.Field FIELD_EventGranularity = SCHEMA.getField("eventGranularity");
    private final static RecordDataSchema.Field FIELD_PartitionSpec = SCHEMA.getField("partitionSpec");
    private final static PartitionSpec DEFAULT_PartitionSpec;
    private final static RecordDataSchema.Field FIELD_MessageId = SCHEMA.getField("messageId");

    static {
        DEFAULT_PartitionSpec = ((FIELD_PartitionSpec.getDefault() == null)?null:new PartitionSpec(DataTemplateUtil.castOrThrow(FIELD_PartitionSpec.getDefault(), DataMap.class)));
    }

    public TimeseriesAspectBase() {
        super(new DataMap(6, 0.75F), SCHEMA, 3);
        addChangeListener(__changeListener);
    }

    public TimeseriesAspectBase(DataMap data) {
        super(data, SCHEMA);
        addChangeListener(__changeListener);
    }

    public static TimeseriesAspectBase.Fields fields() {
        return _fields;
    }

    public static TimeseriesAspectBase.ProjectionMask createMask() {
        return new TimeseriesAspectBase.ProjectionMask();
    }

    public static RecordDataSchema dataSchema() {
        return SCHEMA;
    }

    /**
     * Existence checker for timestampMillis
     * 
     * @see TimeseriesAspectBase.Fields#timestampMillis
     */
    public boolean hasTimestampMillis() {
        if (_timestampMillisField!= null) {
            return true;
        }
        return super._map.containsKey("timestampMillis");
    }

    /**
     * Remover for timestampMillis
     * 
     * @see TimeseriesAspectBase.Fields#timestampMillis
     */
    public void removeTimestampMillis() {
        super._map.remove("timestampMillis");
    }

    /**
     * Getter for timestampMillis
     * 
     * @see TimeseriesAspectBase.Fields#timestampMillis
     */
    @Nullable
    public Long getTimestampMillis(GetMode mode) {
        switch (mode) {
            case STRICT:
                return getTimestampMillis();
            case DEFAULT:
            case NULL:
                if (_timestampMillisField!= null) {
                    return _timestampMillisField;
                } else {
                    Object __rawValue = super._map.get("timestampMillis");
                    _timestampMillisField = DataTemplateUtil.coerceLongOutput(__rawValue);
                    return _timestampMillisField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for timestampMillis
     * 
     * @return
     *     Required field. Could be null for partial record.
     * @see TimeseriesAspectBase.Fields#timestampMillis
     */
    @Nonnull
    public Long getTimestampMillis() {
        if (_timestampMillisField!= null) {
            return _timestampMillisField;
        } else {
            Object __rawValue = super._map.get("timestampMillis");
            if (__rawValue == null) {
                throw new RequiredFieldNotPresentException("timestampMillis");
            }
            _timestampMillisField = DataTemplateUtil.coerceLongOutput(__rawValue);
            return _timestampMillisField;
        }
    }

    /**
     * Setter for timestampMillis
     * 
     * @see TimeseriesAspectBase.Fields#timestampMillis
     */
    public TimeseriesAspectBase setTimestampMillis(
        @Nullable
        Long value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setTimestampMillis(value);
            case REMOVE_OPTIONAL_IF_NULL:
                if (value == null) {
                    throw new IllegalArgumentException("Cannot remove mandatory field timestampMillis of com.linkedin.timeseries.TimeseriesAspectBase");
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "timestampMillis", DataTemplateUtil.coerceLongInput(value));
                    _timestampMillisField = value;
                }
                break;
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeTimestampMillis();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "timestampMillis", DataTemplateUtil.coerceLongInput(value));
                    _timestampMillisField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "timestampMillis", DataTemplateUtil.coerceLongInput(value));
                    _timestampMillisField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for timestampMillis
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see TimeseriesAspectBase.Fields#timestampMillis
     */
    public TimeseriesAspectBase setTimestampMillis(
        @Nonnull
        Long value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field timestampMillis of com.linkedin.timeseries.TimeseriesAspectBase to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "timestampMillis", DataTemplateUtil.coerceLongInput(value));
            _timestampMillisField = value;
        }
        return this;
    }

    /**
     * Setter for timestampMillis
     * 
     * @see TimeseriesAspectBase.Fields#timestampMillis
     */
    public TimeseriesAspectBase setTimestampMillis(long value) {
        CheckedUtil.putWithoutChecking(super._map, "timestampMillis", DataTemplateUtil.coerceLongInput(value));
        _timestampMillisField = value;
        return this;
    }

    /**
     * Existence checker for eventGranularity
     * 
     * @see TimeseriesAspectBase.Fields#eventGranularity
     */
    public boolean hasEventGranularity() {
        if (_eventGranularityField!= null) {
            return true;
        }
        return super._map.containsKey("eventGranularity");
    }

    /**
     * Remover for eventGranularity
     * 
     * @see TimeseriesAspectBase.Fields#eventGranularity
     */
    public void removeEventGranularity() {
        super._map.remove("eventGranularity");
    }

    /**
     * Getter for eventGranularity
     * 
     * @see TimeseriesAspectBase.Fields#eventGranularity
     */
    @Nullable
    public TimeWindowSize getEventGranularity(GetMode mode) {
        return getEventGranularity();
    }

    /**
     * Getter for eventGranularity
     * 
     * @return
     *     Optional field. Always check for null.
     * @see TimeseriesAspectBase.Fields#eventGranularity
     */
    @Nullable
    public TimeWindowSize getEventGranularity() {
        if (_eventGranularityField!= null) {
            return _eventGranularityField;
        } else {
            Object __rawValue = super._map.get("eventGranularity");
            _eventGranularityField = ((__rawValue == null)?null:new TimeWindowSize(DataTemplateUtil.castOrThrow(__rawValue, DataMap.class)));
            return _eventGranularityField;
        }
    }

    /**
     * Setter for eventGranularity
     * 
     * @see TimeseriesAspectBase.Fields#eventGranularity
     */
    public TimeseriesAspectBase setEventGranularity(
        @Nullable
        TimeWindowSize value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setEventGranularity(value);
            case REMOVE_OPTIONAL_IF_NULL:
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeEventGranularity();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "eventGranularity", value.data());
                    _eventGranularityField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "eventGranularity", value.data());
                    _eventGranularityField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for eventGranularity
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see TimeseriesAspectBase.Fields#eventGranularity
     */
    public TimeseriesAspectBase setEventGranularity(
        @Nonnull
        TimeWindowSize value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field eventGranularity of com.linkedin.timeseries.TimeseriesAspectBase to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "eventGranularity", value.data());
            _eventGranularityField = value;
        }
        return this;
    }

    /**
     * Existence checker for partitionSpec
     * 
     * @see TimeseriesAspectBase.Fields#partitionSpec
     */
    public boolean hasPartitionSpec() {
        if (_partitionSpecField!= null) {
            return true;
        }
        return super._map.containsKey("partitionSpec");
    }

    /**
     * Remover for partitionSpec
     * 
     * @see TimeseriesAspectBase.Fields#partitionSpec
     */
    public void removePartitionSpec() {
        super._map.remove("partitionSpec");
    }

    /**
     * Getter for partitionSpec
     * 
     * @see TimeseriesAspectBase.Fields#partitionSpec
     */
    @Nullable
    public PartitionSpec getPartitionSpec(GetMode mode) {
        switch (mode) {
            case STRICT:
            case DEFAULT:
                return getPartitionSpec();
            case NULL:
                if (_partitionSpecField!= null) {
                    return _partitionSpecField;
                } else {
                    Object __rawValue = super._map.get("partitionSpec");
                    _partitionSpecField = ((__rawValue == null)?null:new PartitionSpec(DataTemplateUtil.castOrThrow(__rawValue, DataMap.class)));
                    return _partitionSpecField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for partitionSpec
     * 
     * @return
     *     Optional field. Always check for null.
     * @see TimeseriesAspectBase.Fields#partitionSpec
     */
    @Nullable
    public PartitionSpec getPartitionSpec() {
        if (_partitionSpecField!= null) {
            return _partitionSpecField;
        } else {
            Object __rawValue = super._map.get("partitionSpec");
            if (__rawValue == null) {
                return DEFAULT_PartitionSpec;
            }
            _partitionSpecField = ((__rawValue == null)?null:new PartitionSpec(DataTemplateUtil.castOrThrow(__rawValue, DataMap.class)));
            return _partitionSpecField;
        }
    }

    /**
     * Setter for partitionSpec
     * 
     * @see TimeseriesAspectBase.Fields#partitionSpec
     */
    public TimeseriesAspectBase setPartitionSpec(
        @Nullable
        PartitionSpec value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setPartitionSpec(value);
            case REMOVE_OPTIONAL_IF_NULL:
            case REMOVE_IF_NULL:
                if (value == null) {
                    removePartitionSpec();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "partitionSpec", value.data());
                    _partitionSpecField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "partitionSpec", value.data());
                    _partitionSpecField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for partitionSpec
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see TimeseriesAspectBase.Fields#partitionSpec
     */
    public TimeseriesAspectBase setPartitionSpec(
        @Nonnull
        PartitionSpec value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field partitionSpec of com.linkedin.timeseries.TimeseriesAspectBase to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "partitionSpec", value.data());
            _partitionSpecField = value;
        }
        return this;
    }

    /**
     * Existence checker for messageId
     * 
     * @see TimeseriesAspectBase.Fields#messageId
     */
    public boolean hasMessageId() {
        if (_messageIdField!= null) {
            return true;
        }
        return super._map.containsKey("messageId");
    }

    /**
     * Remover for messageId
     * 
     * @see TimeseriesAspectBase.Fields#messageId
     */
    public void removeMessageId() {
        super._map.remove("messageId");
    }

    /**
     * Getter for messageId
     * 
     * @see TimeseriesAspectBase.Fields#messageId
     */
    @Nullable
    public String getMessageId(GetMode mode) {
        return getMessageId();
    }

    /**
     * Getter for messageId
     * 
     * @return
     *     Optional field. Always check for null.
     * @see TimeseriesAspectBase.Fields#messageId
     */
    @Nullable
    public String getMessageId() {
        if (_messageIdField!= null) {
            return _messageIdField;
        } else {
            Object __rawValue = super._map.get("messageId");
            _messageIdField = DataTemplateUtil.coerceStringOutput(__rawValue);
            return _messageIdField;
        }
    }

    /**
     * Setter for messageId
     * 
     * @see TimeseriesAspectBase.Fields#messageId
     */
    public TimeseriesAspectBase setMessageId(
        @Nullable
        String value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setMessageId(value);
            case REMOVE_OPTIONAL_IF_NULL:
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeMessageId();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "messageId", value);
                    _messageIdField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "messageId", value);
                    _messageIdField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for messageId
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see TimeseriesAspectBase.Fields#messageId
     */
    public TimeseriesAspectBase setMessageId(
        @Nonnull
        String value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field messageId of com.linkedin.timeseries.TimeseriesAspectBase to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "messageId", value);
            _messageIdField = value;
        }
        return this;
    }

    @Override
    public TimeseriesAspectBase clone()
        throws CloneNotSupportedException
    {
        TimeseriesAspectBase __clone = ((TimeseriesAspectBase) super.clone());
        __clone.__changeListener = new TimeseriesAspectBase.ChangeListener(__clone);
        __clone.addChangeListener(__clone.__changeListener);
        return __clone;
    }

    @Override
    public TimeseriesAspectBase copy()
        throws CloneNotSupportedException
    {
        TimeseriesAspectBase __copy = ((TimeseriesAspectBase) super.copy());
        __copy._timestampMillisField = null;
        __copy._eventGranularityField = null;
        __copy._messageIdField = null;
        __copy._partitionSpecField = null;
        __copy.__changeListener = new TimeseriesAspectBase.ChangeListener(__copy);
        __copy.addChangeListener(__copy.__changeListener);
        return __copy;
    }

    private static class ChangeListener
        implements com.linkedin.data.collections.CheckedMap.ChangeListener<String, Object>
    {

        private final TimeseriesAspectBase __objectRef;

        private ChangeListener(TimeseriesAspectBase reference) {
            __objectRef = reference;
        }

        @Override
        public void onUnderlyingMapChanged(String key, Object value) {
            switch (key) {
                case "timestampMillis":
                    __objectRef._timestampMillisField = null;
                    break;
                case "eventGranularity":
                    __objectRef._eventGranularityField = null;
                    break;
                case "messageId":
                    __objectRef._messageIdField = null;
                    break;
                case "partitionSpec":
                    __objectRef._partitionSpecField = null;
                    break;
            }
        }

    }

    public static class Fields
        extends PathSpec
    {


        public Fields(List<String> path, String name) {
            super(path, name);
        }

        public Fields() {
            super();
        }

        /**
         * The event timestamp field as epoch at UTC in milli seconds.
         * 
         */
        public PathSpec timestampMillis() {
            return new PathSpec(getPathComponents(), "timestampMillis");
        }

        /**
         * Granularity of the event if applicable
         * 
         */
        public com.linkedin.timeseries.TimeWindowSize.Fields eventGranularity() {
            return new com.linkedin.timeseries.TimeWindowSize.Fields(getPathComponents(), "eventGranularity");
        }

        /**
         * The optional partition specification.
         * 
         */
        public com.linkedin.timeseries.PartitionSpec.Fields partitionSpec() {
            return new com.linkedin.timeseries.PartitionSpec.Fields(getPathComponents(), "partitionSpec");
        }

        /**
         * The optional messageId, if provided serves as a custom user-defined unique identifier for an aspect value.
         * 
         */
        public PathSpec messageId() {
            return new PathSpec(getPathComponents(), "messageId");
        }

    }

    public static class ProjectionMask
        extends MaskMap
    {

        private com.linkedin.timeseries.TimeWindowSize.ProjectionMask _eventGranularityMask;
        private com.linkedin.timeseries.PartitionSpec.ProjectionMask _partitionSpecMask;

        ProjectionMask() {
            super(6);
        }

        /**
         * The event timestamp field as epoch at UTC in milli seconds.
         * 
         */
        public TimeseriesAspectBase.ProjectionMask withTimestampMillis() {
            getDataMap().put("timestampMillis", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * Granularity of the event if applicable
         * 
         */
        public TimeseriesAspectBase.ProjectionMask withEventGranularity(Function<com.linkedin.timeseries.TimeWindowSize.ProjectionMask, com.linkedin.timeseries.TimeWindowSize.ProjectionMask> nestedMask) {
            _eventGranularityMask = nestedMask.apply(((_eventGranularityMask == null)?TimeWindowSize.createMask():_eventGranularityMask));
            getDataMap().put("eventGranularity", _eventGranularityMask.getDataMap());
            return this;
        }

        /**
         * Granularity of the event if applicable
         * 
         */
        public TimeseriesAspectBase.ProjectionMask withEventGranularity() {
            _eventGranularityMask = null;
            getDataMap().put("eventGranularity", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * The optional partition specification.
         * 
         */
        public TimeseriesAspectBase.ProjectionMask withPartitionSpec(Function<com.linkedin.timeseries.PartitionSpec.ProjectionMask, com.linkedin.timeseries.PartitionSpec.ProjectionMask> nestedMask) {
            _partitionSpecMask = nestedMask.apply(((_partitionSpecMask == null)?PartitionSpec.createMask():_partitionSpecMask));
            getDataMap().put("partitionSpec", _partitionSpecMask.getDataMap());
            return this;
        }

        /**
         * The optional partition specification.
         * 
         */
        public TimeseriesAspectBase.ProjectionMask withPartitionSpec() {
            _partitionSpecMask = null;
            getDataMap().put("partitionSpec", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * The optional messageId, if provided serves as a custom user-defined unique identifier for an aspect value.
         * 
         */
        public TimeseriesAspectBase.ProjectionMask withMessageId() {
            getDataMap().put("messageId", MaskMap.POSITIVE_MASK);
            return this;
        }

    }

}
