
package com.linkedin.identity;

import java.util.List;
import javax.annotation.Generated;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.linkedin.data.DataMap;
import com.linkedin.data.collections.CheckedUtil;
import com.linkedin.data.schema.MaskMap;
import com.linkedin.data.schema.PathSpec;
import com.linkedin.data.schema.RecordDataSchema;
import com.linkedin.data.schema.SchemaFormatType;
import com.linkedin.data.template.DataTemplateUtil;
import com.linkedin.data.template.GetMode;
import com.linkedin.data.template.RecordTemplate;
import com.linkedin.data.template.RequiredFieldNotPresentException;
import com.linkedin.data.template.SetMode;


/**
 * Corp user credentials
 * 
 */
@Generated(value = "com.linkedin.pegasus.generator.JavaCodeUtil", comments = "Rest.li Data Template. Generated from metadata-models/src/main/pegasus/com/linkedin/identity/CorpUserCredentials.pdl.")
public class CorpUserCredentials
    extends RecordTemplate
{

    private final static CorpUserCredentials.Fields _fields = new CorpUserCredentials.Fields();
    private final static RecordDataSchema SCHEMA = ((RecordDataSchema) DataTemplateUtil.parseSchema("namespace com.linkedin.identity/**Corp user credentials*/@Aspect={\"EntityUrns\":[\"com.linkedin.common.CorpuserUrn\"],\"name\":\"corpUserCredentials\"}record CorpUserCredentials{/**Salt used to hash password*/salt:string/**Hashed password generated by concatenating salt and password, then hashing*/hashedPassword:string/**Optional token needed to reset a user's password. Can only be set by the admin.*/passwordResetToken:optional string/**When the password reset token expires.*/passwordResetTokenExpirationTimeMillis:optional long}", SchemaFormatType.PDL));
    private String _saltField = null;
    private String _hashedPasswordField = null;
    private String _passwordResetTokenField = null;
    private Long _passwordResetTokenExpirationTimeMillisField = null;
    private CorpUserCredentials.ChangeListener __changeListener = new CorpUserCredentials.ChangeListener(this);
    private final static RecordDataSchema.Field FIELD_Salt = SCHEMA.getField("salt");
    private final static RecordDataSchema.Field FIELD_HashedPassword = SCHEMA.getField("hashedPassword");
    private final static RecordDataSchema.Field FIELD_PasswordResetToken = SCHEMA.getField("passwordResetToken");
    private final static RecordDataSchema.Field FIELD_PasswordResetTokenExpirationTimeMillis = SCHEMA.getField("passwordResetTokenExpirationTimeMillis");

    public CorpUserCredentials() {
        super(new DataMap(6, 0.75F), SCHEMA);
        addChangeListener(__changeListener);
    }

    public CorpUserCredentials(DataMap data) {
        super(data, SCHEMA);
        addChangeListener(__changeListener);
    }

    public static CorpUserCredentials.Fields fields() {
        return _fields;
    }

    public static CorpUserCredentials.ProjectionMask createMask() {
        return new CorpUserCredentials.ProjectionMask();
    }

    public static RecordDataSchema dataSchema() {
        return SCHEMA;
    }

    /**
     * Existence checker for salt
     * 
     * @see CorpUserCredentials.Fields#salt
     */
    public boolean hasSalt() {
        if (_saltField!= null) {
            return true;
        }
        return super._map.containsKey("salt");
    }

    /**
     * Remover for salt
     * 
     * @see CorpUserCredentials.Fields#salt
     */
    public void removeSalt() {
        super._map.remove("salt");
    }

    /**
     * Getter for salt
     * 
     * @see CorpUserCredentials.Fields#salt
     */
    @Nullable
    public String getSalt(GetMode mode) {
        switch (mode) {
            case STRICT:
                return getSalt();
            case DEFAULT:
            case NULL:
                if (_saltField!= null) {
                    return _saltField;
                } else {
                    Object __rawValue = super._map.get("salt");
                    _saltField = DataTemplateUtil.coerceStringOutput(__rawValue);
                    return _saltField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for salt
     * 
     * @return
     *     Required field. Could be null for partial record.
     * @see CorpUserCredentials.Fields#salt
     */
    @Nonnull
    public String getSalt() {
        if (_saltField!= null) {
            return _saltField;
        } else {
            Object __rawValue = super._map.get("salt");
            if (__rawValue == null) {
                throw new RequiredFieldNotPresentException("salt");
            }
            _saltField = DataTemplateUtil.coerceStringOutput(__rawValue);
            return _saltField;
        }
    }

    /**
     * Setter for salt
     * 
     * @see CorpUserCredentials.Fields#salt
     */
    public CorpUserCredentials setSalt(
        @Nullable
        String value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setSalt(value);
            case REMOVE_OPTIONAL_IF_NULL:
                if (value == null) {
                    throw new IllegalArgumentException("Cannot remove mandatory field salt of com.linkedin.identity.CorpUserCredentials");
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "salt", value);
                    _saltField = value;
                }
                break;
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeSalt();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "salt", value);
                    _saltField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "salt", value);
                    _saltField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for salt
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see CorpUserCredentials.Fields#salt
     */
    public CorpUserCredentials setSalt(
        @Nonnull
        String value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field salt of com.linkedin.identity.CorpUserCredentials to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "salt", value);
            _saltField = value;
        }
        return this;
    }

    /**
     * Existence checker for hashedPassword
     * 
     * @see CorpUserCredentials.Fields#hashedPassword
     */
    public boolean hasHashedPassword() {
        if (_hashedPasswordField!= null) {
            return true;
        }
        return super._map.containsKey("hashedPassword");
    }

    /**
     * Remover for hashedPassword
     * 
     * @see CorpUserCredentials.Fields#hashedPassword
     */
    public void removeHashedPassword() {
        super._map.remove("hashedPassword");
    }

    /**
     * Getter for hashedPassword
     * 
     * @see CorpUserCredentials.Fields#hashedPassword
     */
    @Nullable
    public String getHashedPassword(GetMode mode) {
        switch (mode) {
            case STRICT:
                return getHashedPassword();
            case DEFAULT:
            case NULL:
                if (_hashedPasswordField!= null) {
                    return _hashedPasswordField;
                } else {
                    Object __rawValue = super._map.get("hashedPassword");
                    _hashedPasswordField = DataTemplateUtil.coerceStringOutput(__rawValue);
                    return _hashedPasswordField;
                }
        }
        throw new IllegalStateException(("Unknown mode "+ mode));
    }

    /**
     * Getter for hashedPassword
     * 
     * @return
     *     Required field. Could be null for partial record.
     * @see CorpUserCredentials.Fields#hashedPassword
     */
    @Nonnull
    public String getHashedPassword() {
        if (_hashedPasswordField!= null) {
            return _hashedPasswordField;
        } else {
            Object __rawValue = super._map.get("hashedPassword");
            if (__rawValue == null) {
                throw new RequiredFieldNotPresentException("hashedPassword");
            }
            _hashedPasswordField = DataTemplateUtil.coerceStringOutput(__rawValue);
            return _hashedPasswordField;
        }
    }

    /**
     * Setter for hashedPassword
     * 
     * @see CorpUserCredentials.Fields#hashedPassword
     */
    public CorpUserCredentials setHashedPassword(
        @Nullable
        String value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setHashedPassword(value);
            case REMOVE_OPTIONAL_IF_NULL:
                if (value == null) {
                    throw new IllegalArgumentException("Cannot remove mandatory field hashedPassword of com.linkedin.identity.CorpUserCredentials");
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "hashedPassword", value);
                    _hashedPasswordField = value;
                }
                break;
            case REMOVE_IF_NULL:
                if (value == null) {
                    removeHashedPassword();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "hashedPassword", value);
                    _hashedPasswordField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "hashedPassword", value);
                    _hashedPasswordField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for hashedPassword
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see CorpUserCredentials.Fields#hashedPassword
     */
    public CorpUserCredentials setHashedPassword(
        @Nonnull
        String value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field hashedPassword of com.linkedin.identity.CorpUserCredentials to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "hashedPassword", value);
            _hashedPasswordField = value;
        }
        return this;
    }

    /**
     * Existence checker for passwordResetToken
     * 
     * @see CorpUserCredentials.Fields#passwordResetToken
     */
    public boolean hasPasswordResetToken() {
        if (_passwordResetTokenField!= null) {
            return true;
        }
        return super._map.containsKey("passwordResetToken");
    }

    /**
     * Remover for passwordResetToken
     * 
     * @see CorpUserCredentials.Fields#passwordResetToken
     */
    public void removePasswordResetToken() {
        super._map.remove("passwordResetToken");
    }

    /**
     * Getter for passwordResetToken
     * 
     * @see CorpUserCredentials.Fields#passwordResetToken
     */
    @Nullable
    public String getPasswordResetToken(GetMode mode) {
        return getPasswordResetToken();
    }

    /**
     * Getter for passwordResetToken
     * 
     * @return
     *     Optional field. Always check for null.
     * @see CorpUserCredentials.Fields#passwordResetToken
     */
    @Nullable
    public String getPasswordResetToken() {
        if (_passwordResetTokenField!= null) {
            return _passwordResetTokenField;
        } else {
            Object __rawValue = super._map.get("passwordResetToken");
            _passwordResetTokenField = DataTemplateUtil.coerceStringOutput(__rawValue);
            return _passwordResetTokenField;
        }
    }

    /**
     * Setter for passwordResetToken
     * 
     * @see CorpUserCredentials.Fields#passwordResetToken
     */
    public CorpUserCredentials setPasswordResetToken(
        @Nullable
        String value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setPasswordResetToken(value);
            case REMOVE_OPTIONAL_IF_NULL:
            case REMOVE_IF_NULL:
                if (value == null) {
                    removePasswordResetToken();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "passwordResetToken", value);
                    _passwordResetTokenField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "passwordResetToken", value);
                    _passwordResetTokenField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for passwordResetToken
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see CorpUserCredentials.Fields#passwordResetToken
     */
    public CorpUserCredentials setPasswordResetToken(
        @Nonnull
        String value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field passwordResetToken of com.linkedin.identity.CorpUserCredentials to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "passwordResetToken", value);
            _passwordResetTokenField = value;
        }
        return this;
    }

    /**
     * Existence checker for passwordResetTokenExpirationTimeMillis
     * 
     * @see CorpUserCredentials.Fields#passwordResetTokenExpirationTimeMillis
     */
    public boolean hasPasswordResetTokenExpirationTimeMillis() {
        if (_passwordResetTokenExpirationTimeMillisField!= null) {
            return true;
        }
        return super._map.containsKey("passwordResetTokenExpirationTimeMillis");
    }

    /**
     * Remover for passwordResetTokenExpirationTimeMillis
     * 
     * @see CorpUserCredentials.Fields#passwordResetTokenExpirationTimeMillis
     */
    public void removePasswordResetTokenExpirationTimeMillis() {
        super._map.remove("passwordResetTokenExpirationTimeMillis");
    }

    /**
     * Getter for passwordResetTokenExpirationTimeMillis
     * 
     * @see CorpUserCredentials.Fields#passwordResetTokenExpirationTimeMillis
     */
    @Nullable
    public Long getPasswordResetTokenExpirationTimeMillis(GetMode mode) {
        return getPasswordResetTokenExpirationTimeMillis();
    }

    /**
     * Getter for passwordResetTokenExpirationTimeMillis
     * 
     * @return
     *     Optional field. Always check for null.
     * @see CorpUserCredentials.Fields#passwordResetTokenExpirationTimeMillis
     */
    @Nullable
    public Long getPasswordResetTokenExpirationTimeMillis() {
        if (_passwordResetTokenExpirationTimeMillisField!= null) {
            return _passwordResetTokenExpirationTimeMillisField;
        } else {
            Object __rawValue = super._map.get("passwordResetTokenExpirationTimeMillis");
            _passwordResetTokenExpirationTimeMillisField = DataTemplateUtil.coerceLongOutput(__rawValue);
            return _passwordResetTokenExpirationTimeMillisField;
        }
    }

    /**
     * Setter for passwordResetTokenExpirationTimeMillis
     * 
     * @see CorpUserCredentials.Fields#passwordResetTokenExpirationTimeMillis
     */
    public CorpUserCredentials setPasswordResetTokenExpirationTimeMillis(
        @Nullable
        Long value, SetMode mode) {
        switch (mode) {
            case DISALLOW_NULL:
                return setPasswordResetTokenExpirationTimeMillis(value);
            case REMOVE_OPTIONAL_IF_NULL:
            case REMOVE_IF_NULL:
                if (value == null) {
                    removePasswordResetTokenExpirationTimeMillis();
                } else {
                    CheckedUtil.putWithoutChecking(super._map, "passwordResetTokenExpirationTimeMillis", DataTemplateUtil.coerceLongInput(value));
                    _passwordResetTokenExpirationTimeMillisField = value;
                }
                break;
            case IGNORE_NULL:
                if (value!= null) {
                    CheckedUtil.putWithoutChecking(super._map, "passwordResetTokenExpirationTimeMillis", DataTemplateUtil.coerceLongInput(value));
                    _passwordResetTokenExpirationTimeMillisField = value;
                }
                break;
        }
        return this;
    }

    /**
     * Setter for passwordResetTokenExpirationTimeMillis
     * 
     * @param value
     *     Must not be null. For more control, use setters with mode instead.
     * @see CorpUserCredentials.Fields#passwordResetTokenExpirationTimeMillis
     */
    public CorpUserCredentials setPasswordResetTokenExpirationTimeMillis(
        @Nonnull
        Long value) {
        if (value == null) {
            throw new NullPointerException("Cannot set field passwordResetTokenExpirationTimeMillis of com.linkedin.identity.CorpUserCredentials to null");
        } else {
            CheckedUtil.putWithoutChecking(super._map, "passwordResetTokenExpirationTimeMillis", DataTemplateUtil.coerceLongInput(value));
            _passwordResetTokenExpirationTimeMillisField = value;
        }
        return this;
    }

    /**
     * Setter for passwordResetTokenExpirationTimeMillis
     * 
     * @see CorpUserCredentials.Fields#passwordResetTokenExpirationTimeMillis
     */
    public CorpUserCredentials setPasswordResetTokenExpirationTimeMillis(long value) {
        CheckedUtil.putWithoutChecking(super._map, "passwordResetTokenExpirationTimeMillis", DataTemplateUtil.coerceLongInput(value));
        _passwordResetTokenExpirationTimeMillisField = value;
        return this;
    }

    @Override
    public CorpUserCredentials clone()
        throws CloneNotSupportedException
    {
        CorpUserCredentials __clone = ((CorpUserCredentials) super.clone());
        __clone.__changeListener = new CorpUserCredentials.ChangeListener(__clone);
        __clone.addChangeListener(__clone.__changeListener);
        return __clone;
    }

    @Override
    public CorpUserCredentials copy()
        throws CloneNotSupportedException
    {
        CorpUserCredentials __copy = ((CorpUserCredentials) super.copy());
        __copy._saltField = null;
        __copy._passwordResetTokenExpirationTimeMillisField = null;
        __copy._hashedPasswordField = null;
        __copy._passwordResetTokenField = null;
        __copy.__changeListener = new CorpUserCredentials.ChangeListener(__copy);
        __copy.addChangeListener(__copy.__changeListener);
        return __copy;
    }

    private static class ChangeListener
        implements com.linkedin.data.collections.CheckedMap.ChangeListener<String, Object>
    {

        private final CorpUserCredentials __objectRef;

        private ChangeListener(CorpUserCredentials reference) {
            __objectRef = reference;
        }

        @Override
        public void onUnderlyingMapChanged(String key, Object value) {
            switch (key) {
                case "salt":
                    __objectRef._saltField = null;
                    break;
                case "passwordResetTokenExpirationTimeMillis":
                    __objectRef._passwordResetTokenExpirationTimeMillisField = null;
                    break;
                case "hashedPassword":
                    __objectRef._hashedPasswordField = null;
                    break;
                case "passwordResetToken":
                    __objectRef._passwordResetTokenField = null;
                    break;
            }
        }

    }

    public static class Fields
        extends PathSpec
    {


        public Fields(List<String> path, String name) {
            super(path, name);
        }

        public Fields() {
            super();
        }

        /**
         * Salt used to hash password
         * 
         */
        public PathSpec salt() {
            return new PathSpec(getPathComponents(), "salt");
        }

        /**
         * Hashed password generated by concatenating salt and password, then hashing
         * 
         */
        public PathSpec hashedPassword() {
            return new PathSpec(getPathComponents(), "hashedPassword");
        }

        /**
         * Optional token needed to reset a user's password. Can only be set by the admin.
         * 
         */
        public PathSpec passwordResetToken() {
            return new PathSpec(getPathComponents(), "passwordResetToken");
        }

        /**
         * When the password reset token expires.
         * 
         */
        public PathSpec passwordResetTokenExpirationTimeMillis() {
            return new PathSpec(getPathComponents(), "passwordResetTokenExpirationTimeMillis");
        }

    }

    public static class ProjectionMask
        extends MaskMap
    {


        ProjectionMask() {
            super(6);
        }

        /**
         * Salt used to hash password
         * 
         */
        public CorpUserCredentials.ProjectionMask withSalt() {
            getDataMap().put("salt", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * Hashed password generated by concatenating salt and password, then hashing
         * 
         */
        public CorpUserCredentials.ProjectionMask withHashedPassword() {
            getDataMap().put("hashedPassword", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * Optional token needed to reset a user's password. Can only be set by the admin.
         * 
         */
        public CorpUserCredentials.ProjectionMask withPasswordResetToken() {
            getDataMap().put("passwordResetToken", MaskMap.POSITIVE_MASK);
            return this;
        }

        /**
         * When the password reset token expires.
         * 
         */
        public CorpUserCredentials.ProjectionMask withPasswordResetTokenExpirationTimeMillis() {
            getDataMap().put("passwordResetTokenExpirationTimeMillis", MaskMap.POSITIVE_MASK);
            return this;
        }

    }

}
